name: iOS Homework PR checks (SwiftLint + reviewdog)

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**/*.swift'
      - 'Package.swift'
      - '**/*.xcodeproj/**'
      - '**/*.xcworkspace/**'

permissions:
  contents: read
  pull-requests: write
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_reviewdog:
    name: SwiftLint + reviewdog (inline PR comments)
    runs-on: ubuntu-latest
    # Контейнер со SwiftLint (прибит к digest для безопасности)
    container:
      image: ghcr.io/realm/swiftlint@sha256:6b344b9a236b4367f5a422d78f4ec76014003489d10fc10a4f4466672a9f857e
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Учим линтер "на лету" — проекту ничего не нужно добавлять.
      - name: Generate SwiftLint CI config
        run: |
          cat > .swiftlint-ci.yml <<'YML'
          reporter: checkstyle
          strict: true
          only_rules:
            - attributes
            - closure_spacing
            - colon
            - comma
            - control_statement
            - force_cast
            - force_try
            - force_unwrapping
            - identifier_name
            - opening_brace
            - operator_usage_whitespace
            - redundant_optional_initialization
            - return_arrow_whitespace
            - statement_position
            - trailing_newline
            - trailing_semicolon
            - trailing_whitespace
            - type_name
            - vertical_whitespace
          YML

      # Ставим reviewdog (прибит к коммиту v1.4.0)
      - name: Setup reviewdog
        uses: reviewdog/action-setup@d8edfce3dd5e1ec6978745e801f9c50b5ef80252 # v1.4.0

      # Гоним SwiftLint в checkstyle и отправляем в reviewdog, чтобы он поставил inline-комменты
      - name: Run SwiftLint through reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Не падаем до reviewdog, чтобы комментарии точно отправились
          set +e
          swiftlint lint --config .swiftlint-ci.yml --strict --reporter checkstyle \
            | reviewdog -f=checkstyle -name="SwiftLint" \
                -reporter=github-pr-review \
                -filter-mode=added \
                -level=warning \
                -fail-on-error=false
          # Если хочется фейлить джобу при ошибках — поменяй на: -fail-on-error=true
