name: iOS Homework PR checks (SwiftLint + reviewdog)

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**/*.swift'
      - 'Package.swift'
      - '**/*.xcodeproj/**'
      - '**/*.xcworkspace/**'

permissions:
  contents: read
  pull-requests: write
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_reviewdog:
    name: SwiftLint + reviewdog (inline PR comments)
    runs-on: ubuntu-latest
    container:
      # Можно оставить latest или прижать digest
      image: ghcr.io/realm/swiftlint:latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # 0) Установить curl (и корневые сертификаты) внутри контейнера
      - name: Install curl (container)
        run: |
          set -e
          if command -v apt-get >/dev/null; then
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends curl ca-certificates
            update-ca-certificates || true
          elif command -v apk >/dev/null; then
            apk add --no-cache curl ca-certificates
            update-ca-certificates || true
          elif command -v dnf >/dev/null; then
            dnf -y install curl ca-certificates
          else
            echo "Unknown base image. Install curl manually." >&2
            exit 1
          fi
          curl --version

      # 1) Конфиг SwiftLint для CI — создаём на лету
      - name: Generate SwiftLint CI config
        run: |
          cat > .swiftlint-ci.yml <<'YML'
          reporter: checkstyle
          strict: true
          only_rules:
            - attributes
            - closure_spacing
            - colon
            - comma
            - control_statement
            - force_cast
            - force_try
            - force_unwrapping
            - identifier_name
            - opening_brace
            - operator_usage_whitespace
            - redundant_optional_initialization
            - return_arrow_whitespace
            - statement_position
            - trailing_newline
            - trailing_semicolon
            - trailing_whitespace
            - type_name
            - vertical_whitespace
          YML

      # 2) reviewdog (прибит к коммиту)
      - name: Setup reviewdog
        uses: reviewdog/action-setup@d8edfce3dd5e1ec6978745e801f9c50b5ef80252 # v1.4.0

      # 3) Выбор репортера: review для своих PR, checks для форков
      - name: Choose reviewdog reporter
        run: |
          if [ "${{ github.event.pull_request.head.repo.fork }}" = "true" ]; then
            echo "REPORTER=github-pr-check" >> $GITHUB_ENV
          else
            echo "REPORTER=github-pr-review" >> $GITHUB_ENV
          fi

      # 4) Линт + reviewdog
      - name: Run SwiftLint through reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set +e
          swiftlint lint --config .swiftlint-ci.yml --strict --reporter checkstyle \
            | reviewdog -f=checkstyle -name="SwiftLint" \
                -reporter="${REPORTER}" \
                -filter-mode=added \
                -level=warning \
                -fail-on-error=false
